// Generated by CoffeeScript 1.7.1
(function() {
  $('.content > p > img, .content > p > iframe, .content > p > input').each(function() {
    return $(this).unwrap('p');
  });

  $('.content > iframe').each(function() {
    var isMap, map, source;
    source = $(this).attr('src');
    map = /maps.google/;
    isMap = map.test(source);
    if (isMap) {
      return $(this).wrap('<figure class="map"></figure>');
    } else {
      return $(this).wrap('<figure class="video"></figure>');
    }
  });

  $('.content > img, .content > p > img').wrap('<figure></figure>');

  $('.video').fitVids();

}).call(this);
