// Generated by CoffeeScript 1.7.1
(function() {
  $('[placeholder]').each(function() {
    var hint;
    if ($(this).val() === '') {
      hint = $(this).attr('placeholder');
      return $(this).val(hint).addClass('hint');
    }
  });

  $('[placeholder]').focus(function() {
    if ($(this).val() === $(this).attr('placeholder')) {
      return $(this).val('').removeClass('hint');
    }
  }).blur(function() {
    if ($(this).val() === '') {
      return $(this).val($(this).attr('placeholder')).addClass('hint');
    }
  });

}).call(this);
