// Generated by CoffeeScript 1.7.1
(function() {
  $('.tabs').each(function() {
    var $active, $content, $links;
    $links = $(this).find('a');
    $active = $($links.filter('[href=\'' + location.hash + '\']')[0] || $links[0]);
    $active.addClass('active');
    $content = $($active.attr('href'));
    $links.not($active).each(function() {
      return $($(this).attr('href')).hide();
    });
    return $(this).on('click', 'a', function(e) {
      $active.removeClass('active');
      $content.hide();
      $active = $(this);
      $content = $($(this).attr('href'));
      $active.addClass('active');
      $content.show();
      return e.preventDefault();
    });
  });

}).call(this);
