// Generated by CoffeeScript 1.7.1
(function() {
  $('.js-show-pw').click(function(e) {
    var type;
    type = $(this).parents('.field').find('input');
    if ($(type).attr('type') === 'text') {
      $(type).get(0).type = 'password';
      $(this).text('Show password');
    } else {
      $(type).get(0).type = 'text';
      $(this).text('Hide password');
    }
    return e.preventDefault();
  });

  $('.js-options input').change(function() {
    var check, type;
    type = $(this).attr('type');
    check = $(this).parent('label');
    if (type === 'checkbox') {
      return check.toggleClass('checked');
    } else if (type === 'radio') {
      check.siblings('label').removeClass('checked');
      return check.addClass('checked');
    }
  });

}).call(this);
