// Generated by CoffeeScript 1.7.1
(function() {
  $('.js-open-canvas').click(function(e) {
    var target, targetName;
    target = $(this).find('a').attr('href');
    targetName = target.substring(4);
    $(this).toggleClass('active');
    $(target).toggleClass('offcanvas--open');
    $('body').toggleClass('offcanvas--push-' + targetName);
    return e.preventDefault();
  });

}).call(this);
