// Generated by CoffeeScript 1.4.0

$(function() {
  return $('.reveal').click(function() {
    var target;
    target = $(this).attr('href');
    $(target).slideToggle('fast');
    return false;
  });
});
