// Generated by CoffeeScript 1.7.1
(function() {
  $('h1:contains("&"),h2:contains("&"),h3:contains("&"),h4:contains("&"),h5:contains("&"),h6:contains("&"),.lead:contains("&"),.content > p:first-child:contains("&")').each(function() {
    return $(this).html($(this).html().replace(/&amp;/, "<abbr class='amp'>&amp;</abbr>"));
  });

}).call(this);
